- type: job
  id: BrigMed
  name: job-name-brigmedic
  description: job-description-brigmedic
  playTimeTracker: JobBrigMed
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 108000 # Corvax-RoleTime
  startingGear: BrigmedicGear
  icon: "JobIconBrigmedic"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Brig
  - Security
  - Maintenance
  - Service
  - External
  - Cryogenics
  - Medical
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
  